//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.13 at 04:29:55 PM IST 
//


package com.hcl.msa.parser.xml.struts.struts2.jaxbmodel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hcl.msa.parser.xml.struts.struts2.jaxbmodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hcl.msa.parser.xml.struts.struts2.jaxbmodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DefaultActionRef }
     * 
     */
    public DefaultActionRef createDefaultActionRef() {
        return new DefaultActionRef();
    }

    /**
     * Create an instance of {@link Include }
     * 
     */
    public Include createInclude() {
        return new Include();
    }

    /**
     * Create an instance of {@link Package }
     * 
     */
    public Package createPackage() {
        return new Package();
    }

    /**
     * Create an instance of {@link ResultTypes }
     * 
     */
    public ResultTypes createResultTypes() {
        return new ResultTypes();
    }

    /**
     * Create an instance of {@link Interceptors }
     * 
     */
    public Interceptors createInterceptors() {
        return new Interceptors();
    }

    /**
     * Create an instance of {@link DefaultInterceptorRef }
     * 
     */
    public DefaultInterceptorRef createDefaultInterceptorRef() {
        return new DefaultInterceptorRef();
    }

    /**
     * Create an instance of {@link DefaultClassRef }
     * 
     */
    public DefaultClassRef createDefaultClassRef() {
        return new DefaultClassRef();
    }

    /**
     * Create an instance of {@link GlobalResults }
     * 
     */
    public GlobalResults createGlobalResults() {
        return new GlobalResults();
    }

    /**
     * Create an instance of {@link GlobalExceptionMappings }
     * 
     */
    public GlobalExceptionMappings createGlobalExceptionMappings() {
        return new GlobalExceptionMappings();
    }

    /**
     * Create an instance of {@link Action }
     * 
     */
    public Action createAction() {
        return new Action();
    }

    /**
     * Create an instance of {@link Constant }
     * 
     */
    public Constant createConstant() {
        return new Constant();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link Interceptor }
     * 
     */
    public Interceptor createInterceptor() {
        return new Interceptor();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link InterceptorStack }
     * 
     */
    public InterceptorStack createInterceptorStack() {
        return new InterceptorStack();
    }

    /**
     * Create an instance of {@link InterceptorRef }
     * 
     */
    public InterceptorRef createInterceptorRef() {
        return new InterceptorRef();
    }

    /**
     * Create an instance of {@link ExceptionMapping }
     * 
     */
    public ExceptionMapping createExceptionMapping() {
        return new ExceptionMapping();
    }

    /**
     * Create an instance of {@link Struts }
     * 
     */
    public Struts createStruts() {
        return new Struts();
    }

    /**
     * Create an instance of {@link Bean }
     * 
     */
    public Bean createBean() {
        return new Bean();
    }

    /**
     * Create an instance of {@link ResultType }
     * 
     */
    public ResultType createResultType() {
        return new ResultType();
    }

}
