//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.13 at 04:29:55 PM IST 
//


package com.hcl.msa.parser.xml.struts.struts2.jaxbmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "resultTypes",
    "interceptors",
    "defaultInterceptorRef",
    "defaultActionRef",
    "defaultClassRef",
    "globalResults",
    "globalExceptionMappings",
    "action"
})
@XmlRootElement(name = "package")
public class Package {

    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "extends")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String _extends;
    @XmlAttribute(name = "namespace")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String namespace;
    @XmlAttribute(name = "abstract")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String _abstract;
    @XmlAttribute(name = "externalReferenceResolver")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String externalReferenceResolver;
    @XmlElement(name = "result-types")
    protected ResultTypes resultTypes;
    protected Interceptors interceptors;
    @XmlElement(name = "default-interceptor-ref")
    protected DefaultInterceptorRef defaultInterceptorRef;
    @XmlElement(name = "default-action-ref")
    protected DefaultActionRef defaultActionRef;
    @XmlElement(name = "default-class-ref")
    protected DefaultClassRef defaultClassRef;
    @XmlElement(name = "global-results")
    protected GlobalResults globalResults;
    @XmlElement(name = "global-exception-mappings")
    protected GlobalExceptionMappings globalExceptionMappings;
    protected List<Action> action;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the extends property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtends() {
        return _extends;
    }

    /**
     * Sets the value of the extends property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtends(String value) {
        this._extends = value;
    }

    /**
     * Gets the value of the namespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * Sets the value of the namespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamespace(String value) {
        this.namespace = value;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbstract(String value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the externalReferenceResolver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalReferenceResolver() {
        return externalReferenceResolver;
    }

    /**
     * Sets the value of the externalReferenceResolver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalReferenceResolver(String value) {
        this.externalReferenceResolver = value;
    }

    /**
     * Gets the value of the resultTypes property.
     * 
     * @return
     *     possible object is
     *     {@link ResultTypes }
     *     
     */
    public ResultTypes getResultTypes() {
        return resultTypes;
    }

    /**
     * Sets the value of the resultTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultTypes }
     *     
     */
    public void setResultTypes(ResultTypes value) {
        this.resultTypes = value;
    }

    /**
     * Gets the value of the interceptors property.
     * 
     * @return
     *     possible object is
     *     {@link Interceptors }
     *     
     */
    public Interceptors getInterceptors() {
        return interceptors;
    }

    /**
     * Sets the value of the interceptors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interceptors }
     *     
     */
    public void setInterceptors(Interceptors value) {
        this.interceptors = value;
    }

    /**
     * Gets the value of the defaultInterceptorRef property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultInterceptorRef }
     *     
     */
    public DefaultInterceptorRef getDefaultInterceptorRef() {
        return defaultInterceptorRef;
    }

    /**
     * Sets the value of the defaultInterceptorRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultInterceptorRef }
     *     
     */
    public void setDefaultInterceptorRef(DefaultInterceptorRef value) {
        this.defaultInterceptorRef = value;
    }

    /**
     * Gets the value of the defaultActionRef property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultActionRef }
     *     
     */
    public DefaultActionRef getDefaultActionRef() {
        return defaultActionRef;
    }

    /**
     * Sets the value of the defaultActionRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultActionRef }
     *     
     */
    public void setDefaultActionRef(DefaultActionRef value) {
        this.defaultActionRef = value;
    }

    /**
     * Gets the value of the defaultClassRef property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultClassRef }
     *     
     */
    public DefaultClassRef getDefaultClassRef() {
        return defaultClassRef;
    }

    /**
     * Sets the value of the defaultClassRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultClassRef }
     *     
     */
    public void setDefaultClassRef(DefaultClassRef value) {
        this.defaultClassRef = value;
    }

    /**
     * Gets the value of the globalResults property.
     * 
     * @return
     *     possible object is
     *     {@link GlobalResults }
     *     
     */
    public GlobalResults getGlobalResults() {
        return globalResults;
    }

    /**
     * Sets the value of the globalResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlobalResults }
     *     
     */
    public void setGlobalResults(GlobalResults value) {
        this.globalResults = value;
    }

    /**
     * Gets the value of the globalExceptionMappings property.
     * 
     * @return
     *     possible object is
     *     {@link GlobalExceptionMappings }
     *     
     */
    public GlobalExceptionMappings getGlobalExceptionMappings() {
        return globalExceptionMappings;
    }

    /**
     * Sets the value of the globalExceptionMappings property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlobalExceptionMappings }
     *     
     */
    public void setGlobalExceptionMappings(GlobalExceptionMappings value) {
        this.globalExceptionMappings = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the action property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Action }
     * 
     * 
     */
    public List<Action> getAction() {
        if (action == null) {
            action = new ArrayList<Action>();
        }
        return this.action;
    }

}
