//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.13 at 04:29:55 PM IST 
//


package com.hcl.msa.parser.xml.struts.struts2.jaxbmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "packageOrIncludeOrBeanOrConstant"
})
@XmlRootElement(name = "struts")
public class Struts {

    @XmlElements({
        @XmlElement(name = "package", type = Package.class),
        @XmlElement(name = "include", type = Include.class),
        @XmlElement(name = "bean", type = Bean.class),
        @XmlElement(name = "constant", type = Constant.class)
    })
    protected List<Object> packageOrIncludeOrBeanOrConstant;

    /**
     * Gets the value of the packageOrIncludeOrBeanOrConstant property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the packageOrIncludeOrBeanOrConstant property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPackageOrIncludeOrBeanOrConstant().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Package }
     * {@link Include }
     * {@link Bean }
     * {@link Constant }
     * 
     * 
     */
    public List<Object> getPackageOrIncludeOrBeanOrConstant() {
        if (packageOrIncludeOrBeanOrConstant == null) {
            packageOrIncludeOrBeanOrConstant = new ArrayList<Object>();
        }
        return this.packageOrIncludeOrBeanOrConstant;
    }

}
