//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.13 at 04:09:38 PM IST 
//


package com.hcl.msa.parser.xml.struts.struts13.jaxbmodel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hcl.msa.parser.xml.struts.struts1.jaxbmodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hcl.msa.parser.xml.struts.struts1.jaxbmodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FormBeans }
     * 
     */
    public FormBeans createFormBeans() {
        return new FormBeans();
    }

    /**
     * Create an instance of {@link FormBean }
     * 
     */
    public FormBean createFormBean() {
        return new FormBean();
    }

    /**
     * Create an instance of {@link Exception }
     * 
     */
    public Exception createException() {
        return new Exception();
    }

    /**
     * Create an instance of {@link Icon }
     * 
     */
    public Icon createIcon() {
        return new Icon();
    }

    /**
     * Create an instance of {@link DisplayName }
     * 
     */
    public DisplayName createDisplayName() {
        return new DisplayName();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link SetProperty }
     * 
     */
    public SetProperty createSetProperty() {
        return new SetProperty();
    }

    /**
     * Create an instance of {@link PlugIn }
     * 
     */
    public PlugIn createPlugIn() {
        return new PlugIn();
    }

    /**
     * Create an instance of {@link Controller }
     * 
     */
    public Controller createController() {
        return new Controller();
    }

    /**
     * Create an instance of {@link ActionMappings }
     * 
     */
    public ActionMappings createActionMappings() {
        return new ActionMappings();
    }

    /**
     * Create an instance of {@link Action }
     * 
     */
    public Action createAction() {
        return new Action();
    }

    /**
     * Create an instance of {@link Forward }
     * 
     */
    public Forward createForward() {
        return new Forward();
    }

    /**
     * Create an instance of {@link StrutsConfig }
     * 
     */
    public StrutsConfig createStrutsConfig() {
        return new StrutsConfig();
    }

    /**
     * Create an instance of {@link GlobalExceptions }
     * 
     */
    public GlobalExceptions createGlobalExceptions() {
        return new GlobalExceptions();
    }

    /**
     * Create an instance of {@link GlobalForwards }
     * 
     */
    public GlobalForwards createGlobalForwards() {
        return new GlobalForwards();
    }

    /**
     * Create an instance of {@link MessageResources }
     * 
     */
    public MessageResources createMessageResources() {
        return new MessageResources();
    }

    /**
     * Create an instance of {@link SmallIcon }
     * 
     */
    public SmallIcon createSmallIcon() {
        return new SmallIcon();
    }

    /**
     * Create an instance of {@link LargeIcon }
     * 
     */
    public LargeIcon createLargeIcon() {
        return new LargeIcon();
    }

    /**
     * Create an instance of {@link FormProperty }
     * 
     */
    public FormProperty createFormProperty() {
        return new FormProperty();
    }

}
