//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.17 at 04:45:32 PM IST 
//


package com.hcl.msa.parser.xml.ejb.ejb21.jaxbmodel;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hcl.msa.parser.xml.ejb.ejb21.jaxbmodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EjbJar_QNAME = new QName("http://java.sun.com/xml/ns/j2ee", "ejb-jar");
    private final static QName _EjbRelationDescription_QNAME = new QName("http://java.sun.com/xml/ns/j2ee", "description");
    private final static QName _EjbRelationEjbRelationName_QNAME = new QName("http://java.sun.com/xml/ns/j2ee", "ejb-relation-name");
    private final static QName _EjbRelationEjbRelationshipRole_QNAME = new QName("http://java.sun.com/xml/ns/j2ee", "ejb-relationship-role");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hcl.msa.parser.xml.ejb.ejb21.jaxbmodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EjbJar }
     * 
     */
    public EjbJar createEjbJar() {
        return new EjbJar();
    }

    /**
     * Create an instance of {@link Multiplicity }
     * 
     */
    public Multiplicity createMultiplicity() {
        return new Multiplicity();
    }

    /**
     * Create an instance of {@link ServiceRef }
     * 
     */
    public ServiceRef createServiceRef() {
        return new ServiceRef();
    }

    /**
     * Create an instance of {@link Listener }
     * 
     */
    public Listener createListener() {
        return new Listener();
    }

    /**
     * Create an instance of {@link QueryMethod }
     * 
     */
    public QueryMethod createQueryMethod() {
        return new QueryMethod();
    }

    /**
     * Create an instance of {@link RelationshipRoleSource }
     * 
     */
    public RelationshipRoleSource createRelationshipRoleSource() {
        return new RelationshipRoleSource();
    }

    /**
     * Create an instance of {@link PortComponentRef }
     * 
     */
    public PortComponentRef createPortComponentRef() {
        return new PortComponentRef();
    }

    /**
     * Create an instance of {@link MethodName }
     * 
     */
    public MethodName createMethodName() {
        return new MethodName();
    }

    /**
     * Create an instance of {@link EjbLocalRef }
     * 
     */
    public EjbLocalRef createEjbLocalRef() {
        return new EjbLocalRef();
    }

    /**
     * Create an instance of {@link Remote }
     * 
     */
    public Remote createRemote() {
        return new Remote();
    }

    /**
     * Create an instance of {@link EjbRelation }
     * 
     */
    public EjbRelation createEjbRelation() {
        return new EjbRelation();
    }

    /**
     * Create an instance of {@link Empty }
     * 
     */
    public Empty createEmpty() {
        return new Empty();
    }

    /**
     * Create an instance of {@link EjbRef }
     * 
     */
    public EjbRef createEjbRef() {
        return new EjbRef();
    }

    /**
     * Create an instance of {@link Path }
     * 
     */
    public Path createPath() {
        return new Path();
    }

    /**
     * Create an instance of {@link Relationships }
     * 
     */
    public Relationships createRelationships() {
        return new Relationships();
    }

    /**
     * Create an instance of {@link EjbRelationshipRole }
     * 
     */
    public EjbRelationshipRole createEjbRelationshipRole() {
        return new EjbRelationshipRole();
    }

    /**
     * Create an instance of {@link SecurityRoleRef }
     * 
     */
    public SecurityRoleRef createSecurityRoleRef() {
        return new SecurityRoleRef();
    }

    /**
     * Create an instance of {@link EnterpriseBeans }
     * 
     */
    public EnterpriseBeans createEnterpriseBeans() {
        return new EnterpriseBeans();
    }

    /**
     * Create an instance of {@link ParamValue }
     * 
     */
    public ParamValue createParamValue() {
        return new ParamValue();
    }

    /**
     * Create an instance of {@link CmpField }
     * 
     */
    public CmpField createCmpField() {
        return new CmpField();
    }

    /**
     * Create an instance of {@link MessageDestinationRef }
     * 
     */
    public MessageDestinationRef createMessageDestinationRef() {
        return new MessageDestinationRef();
    }

    /**
     * Create an instance of {@link ActivationConfig }
     * 
     */
    public ActivationConfig createActivationConfig() {
        return new ActivationConfig();
    }

    /**
     * Create an instance of {@link ServiceRefHandler }
     * 
     */
    public ServiceRefHandler createServiceRefHandler() {
        return new ServiceRefHandler();
    }

    /**
     * Create an instance of {@link PersistenceType }
     * 
     */
    public PersistenceType createPersistenceType() {
        return new PersistenceType();
    }

    /**
     * Create an instance of {@link RunAs }
     * 
     */
    public RunAs createRunAs() {
        return new RunAs();
    }

    /**
     * Create an instance of {@link MessageDrivenBean }
     * 
     */
    public MessageDrivenBean createMessageDrivenBean() {
        return new MessageDrivenBean();
    }

    /**
     * Create an instance of {@link TransAttribute }
     * 
     */
    public TransAttribute createTransAttribute() {
        return new TransAttribute();
    }

    /**
     * Create an instance of {@link Method }
     * 
     */
    public Method createMethod() {
        return new Method();
    }

    /**
     * Create an instance of {@link SecurityIdentity }
     * 
     */
    public SecurityIdentity createSecurityIdentity() {
        return new SecurityIdentity();
    }

    /**
     * Create an instance of {@link SecurityRole }
     * 
     */
    public SecurityRole createSecurityRole() {
        return new SecurityRole();
    }

    /**
     * Create an instance of {@link Query }
     * 
     */
    public Query createQuery() {
        return new Query();
    }

    /**
     * Create an instance of {@link AssemblyDescriptor }
     * 
     */
    public AssemblyDescriptor createAssemblyDescriptor() {
        return new AssemblyDescriptor();
    }

    /**
     * Create an instance of {@link XsdBoolean }
     * 
     */
    public XsdBoolean createXsdBoolean() {
        return new XsdBoolean();
    }

    /**
     * Create an instance of {@link CmrFieldType }
     * 
     */
    public CmrFieldType createCmrFieldType() {
        return new CmrFieldType();
    }

    /**
     * Create an instance of {@link TrueFalse }
     * 
     */
    public TrueFalse createTrueFalse() {
        return new TrueFalse();
    }

    /**
     * Create an instance of {@link EjbRefName }
     * 
     */
    public EjbRefName createEjbRefName() {
        return new EjbRefName();
    }

    /**
     * Create an instance of {@link UrlPattern }
     * 
     */
    public UrlPattern createUrlPattern() {
        return new UrlPattern();
    }

    /**
     * Create an instance of {@link DisplayName }
     * 
     */
    public DisplayName createDisplayName() {
        return new DisplayName();
    }

    /**
     * Create an instance of {@link ResAuth }
     * 
     */
    public ResAuth createResAuth() {
        return new ResAuth();
    }

    /**
     * Create an instance of {@link MethodIntf }
     * 
     */
    public MethodIntf createMethodIntf() {
        return new MethodIntf();
    }

    /**
     * Create an instance of {@link GenericBoolean }
     * 
     */
    public GenericBoolean createGenericBoolean() {
        return new GenericBoolean();
    }

    /**
     * Create an instance of {@link XsdInteger }
     * 
     */
    public XsdInteger createXsdInteger() {
        return new XsdInteger();
    }

    /**
     * Create an instance of {@link MessageDestinationLink }
     * 
     */
    public MessageDestinationLink createMessageDestinationLink() {
        return new MessageDestinationLink();
    }

    /**
     * Create an instance of {@link RoleName }
     * 
     */
    public RoleName createRoleName() {
        return new RoleName();
    }

    /**
     * Create an instance of {@link ContainerTransaction }
     * 
     */
    public ContainerTransaction createContainerTransaction() {
        return new ContainerTransaction();
    }

    /**
     * Create an instance of {@link CmrField }
     * 
     */
    public CmrField createCmrField() {
        return new CmrField();
    }

    /**
     * Create an instance of {@link String }
     * 
     */
    public String createString() {
        return new String();
    }

    /**
     * Create an instance of {@link ActivationConfigProperty }
     * 
     */
    public ActivationConfigProperty createActivationConfigProperty() {
        return new ActivationConfigProperty();
    }

    /**
     * Create an instance of {@link EjbClass }
     * 
     */
    public EjbClass createEjbClass() {
        return new EjbClass();
    }

    /**
     * Create an instance of {@link EntityBean }
     * 
     */
    public EntityBean createEntityBean() {
        return new EntityBean();
    }

    /**
     * Create an instance of {@link Icon }
     * 
     */
    public Icon createIcon() {
        return new Icon();
    }

    /**
     * Create an instance of {@link MessageDestination }
     * 
     */
    public MessageDestination createMessageDestination() {
        return new MessageDestination();
    }

    /**
     * Create an instance of {@link MethodPermission }
     * 
     */
    public MethodPermission createMethodPermission() {
        return new MethodPermission();
    }

    /**
     * Create an instance of {@link SessionBean }
     * 
     */
    public SessionBean createSessionBean() {
        return new SessionBean();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link SessionType }
     * 
     */
    public SessionType createSessionType() {
        return new SessionType();
    }

    /**
     * Create an instance of {@link XsdNonNegativeInteger }
     * 
     */
    public XsdNonNegativeInteger createXsdNonNegativeInteger() {
        return new XsdNonNegativeInteger();
    }

    /**
     * Create an instance of {@link XsdPositiveInteger }
     * 
     */
    public XsdPositiveInteger createXsdPositiveInteger() {
        return new XsdPositiveInteger();
    }

    /**
     * Create an instance of {@link EnvEntryTypeValues }
     * 
     */
    public EnvEntryTypeValues createEnvEntryTypeValues() {
        return new EnvEntryTypeValues();
    }

    /**
     * Create an instance of {@link Local }
     * 
     */
    public Local createLocal() {
        return new Local();
    }

    /**
     * Create an instance of {@link ResourceRef }
     * 
     */
    public ResourceRef createResourceRef() {
        return new ResourceRef();
    }

    /**
     * Create an instance of {@link XsdAnyURI }
     * 
     */
    public XsdAnyURI createXsdAnyURI() {
        return new XsdAnyURI();
    }

    /**
     * Create an instance of {@link ResultTypeMapping }
     * 
     */
    public ResultTypeMapping createResultTypeMapping() {
        return new ResultTypeMapping();
    }

    /**
     * Create an instance of {@link ResSharingScope }
     * 
     */
    public ResSharingScope createResSharingScope() {
        return new ResSharingScope();
    }

    /**
     * Create an instance of {@link XsdString }
     * 
     */
    public XsdString createXsdString() {
        return new XsdString();
    }

    /**
     * Create an instance of {@link MessageDestinationUsage }
     * 
     */
    public MessageDestinationUsage createMessageDestinationUsage() {
        return new MessageDestinationUsage();
    }

    /**
     * Create an instance of {@link ExcludeList }
     * 
     */
    public ExcludeList createExcludeList() {
        return new ExcludeList();
    }

    /**
     * Create an instance of {@link TransactionType }
     * 
     */
    public TransactionType createTransactionType() {
        return new TransactionType();
    }

    /**
     * Create an instance of {@link JavaIdentifier }
     * 
     */
    public JavaIdentifier createJavaIdentifier() {
        return new JavaIdentifier();
    }

    /**
     * Create an instance of {@link XsdNMTOKEN }
     * 
     */
    public XsdNMTOKEN createXsdNMTOKEN() {
        return new XsdNMTOKEN();
    }

    /**
     * Create an instance of {@link CmpVersion }
     * 
     */
    public CmpVersion createCmpVersion() {
        return new CmpVersion();
    }

    /**
     * Create an instance of {@link EjbRefType }
     * 
     */
    public EjbRefType createEjbRefType() {
        return new EjbRefType();
    }

    /**
     * Create an instance of {@link EjbName }
     * 
     */
    public EjbName createEjbName() {
        return new EjbName();
    }

    /**
     * Create an instance of {@link XsdQName }
     * 
     */
    public XsdQName createXsdQName() {
        return new XsdQName();
    }

    /**
     * Create an instance of {@link FullyQualifiedClass }
     * 
     */
    public FullyQualifiedClass createFullyQualifiedClass() {
        return new FullyQualifiedClass();
    }

    /**
     * Create an instance of {@link LocalHome }
     * 
     */
    public LocalHome createLocalHome() {
        return new LocalHome();
    }

    /**
     * Create an instance of {@link ResourceEnvRef }
     * 
     */
    public ResourceEnvRef createResourceEnvRef() {
        return new ResourceEnvRef();
    }

    /**
     * Create an instance of {@link MethodParams }
     * 
     */
    public MethodParams createMethodParams() {
        return new MethodParams();
    }

    /**
     * Create an instance of {@link Home }
     * 
     */
    public Home createHome() {
        return new Home();
    }

    /**
     * Create an instance of {@link JndiName }
     * 
     */
    public JndiName createJndiName() {
        return new JndiName();
    }

    /**
     * Create an instance of {@link EjbLink }
     * 
     */
    public EjbLink createEjbLink() {
        return new EjbLink();
    }

    /**
     * Create an instance of {@link MessageDestinationType }
     * 
     */
    public MessageDestinationType createMessageDestinationType() {
        return new MessageDestinationType();
    }

    /**
     * Create an instance of {@link JavaType }
     * 
     */
    public JavaType createJavaType() {
        return new JavaType();
    }

    /**
     * Create an instance of {@link EnvEntry }
     * 
     */
    public EnvEntry createEnvEntry() {
        return new EnvEntry();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EjbJar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/j2ee", name = "ejb-jar")
    public JAXBElement<EjbJar> createEjbJar(EjbJar value) {
        return new JAXBElement<EjbJar>(_EjbJar_QNAME, EjbJar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Description }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/j2ee", name = "description", scope = EjbRelation.class)
    public JAXBElement<Description> createEjbRelationDescription(Description value) {
        return new JAXBElement<Description>(_EjbRelationDescription_QNAME, Description.class, EjbRelation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/j2ee", name = "ejb-relation-name", scope = EjbRelation.class)
    public JAXBElement<String> createEjbRelationEjbRelationName(String value) {
        return new JAXBElement<String>(_EjbRelationEjbRelationName_QNAME, String.class, EjbRelation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EjbRelationshipRole }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/j2ee", name = "ejb-relationship-role", scope = EjbRelation.class)
    public JAXBElement<EjbRelationshipRole> createEjbRelationEjbRelationshipRole(EjbRelationshipRole value) {
        return new JAXBElement<EjbRelationshipRole>(_EjbRelationEjbRelationshipRole_QNAME, EjbRelationshipRole.class, EjbRelation.class, value);
    }

}
